apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: share-my-files
  name: share-my-files
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: share-my-files
  template:
    metadata:
      labels:
        app: share-my-files
    spec:
      containers:
      - image: share-my-files
        name: share-my-files
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: share-my-files
spec:
  type: LoadBalancer
  selector:
    app: share-my-files
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080