apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: share-my-files
  name: share-my-files
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: share-my-files
  template:
    metadata:
      labels:
        app: share-my-files
    spec:
      containers:
      - image: share-my-files
        name: share-my-files
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
        env:
        - name: REDIS_ADDR
          value: "redis.auxiliary.svc.cluster.local:6379"
        - name: DDNS_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DDNS_ADDRESS
        - name: MAX_FILE_SIZE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MAX_FILE_SIZE

---
apiVersion: v1
kind: Service
metadata:
  name: share-my-files
  namespace: applications
spec:
  type: LoadBalancer
  selector:
    app: share-my-files
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: applications
data:
  DDNS_ADDRESS: "http://diskbirds.tplinkdns.com"
  MAX_FILE_SIZE: "10" # size in bytes