apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "share-my-files.fullname" . }}
  labels:
    {{- include "share-my-files.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/share-my-files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "share-my-files.fullname" . }}
  labels:
    {{- include "share-my-files.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard