apiVersion: v1
kind: Secret
metadata:
  name: {{ include "share-my-files.fullname" . }}
  labels:
    {{- include "share-my-files.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.password | b64enc | quote }}
  tls.key: {{ .Values.password | b64enc | quote }}